In [2]:
# Numpy:PAckage for Multidimensional array

import numpy as np
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
 np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [11]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.random.rand(3,2)

array([[0.67431467, 0.29738142],
       [0.1499518 , 0.7090513 ],
       [0.42784293, 0.67351529]])

In [22]:
np.random.randn(1,5)

array([[-0.39260371, -2.36563757, -0.20823508, -0.90993332, -0.34348092]])

In [23]:
np.random.randint(1,5)

4

In [24]:
np.random.randint(34,100,50)

array([60, 73, 96, 69, 65, 48, 95, 85, 79, 94, 95, 47, 45, 83, 91, 45, 50,
       80, 51, 94, 37, 64, 42, 52, 97, 95, 65, 98, 88, 50, 77, 67, 77, 95,
       91, 87, 76, 50, 39, 71, 77, 92, 68, 52, 76, 70, 78, 73, 98, 67])

In [26]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
rand_array=np.random.randint(0,100,20)
rand_array

array([78, 62, 40, 44,  3, 14, 40, 21,  8, 82, 88,  3, 64, 30,  2, 60, 85,
       74, 50, 50])

In [30]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [31]:
sample_array.reshape(4,7)

ValueError: ignored

In [32]:
sample_array.reshape(3,11)

ValueError: ignored

In [33]:
rand_array.min()

2

In [35]:
rand_array.argmin()

14

In [37]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
a=np.random.rand(2,3)
a

array([[0.59296208, 0.63937847, 0.746532  ],
       [0.14369985, 0.55725568, 0.09129117]])

In [43]:
a.T

array([[0.59296208, 0.14369985],
       [0.63937847, 0.55725568],
       [0.746532  , 0.09129117]])

In [44]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [45]:
sample_array[3]

13

In [46]:
sample_array[3:7]

array([13, 14, 15, 16])

In [48]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [49]:
subset_sample_array=sample_array[1:4]
subset_sample_array

array([100, 100, 100])

In [51]:
sample_array[:]=1001
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [55]:
# Two Dimensional Array

import numpy as np

sample_matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
sample_matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
sample_matrix[0:2,2]

array([3, 6])

In [57]:
sample_matrix[2,:]

array([7, 8, 9])

In [58]:
sample_matrix[2]

array([7, 8, 9])

In [61]:
# [rows,columns]
sample_matrix[:,(1,2)]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [3]:
import numpy as np
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [4]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [5]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [6]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [7]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [8]:
np.max(sample_array)

19

In [9]:
np.min(sample_array)

1

In [10]:
np.argmax(sample_array)

18

In [11]:
np.argmin(sample_array)

0

In [12]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [13]:
np.std(sample_array)

5.477225575051661

In [14]:
np.mean(sample_array)

10.0

In [15]:
np.var(sample_array)

30.0

In [19]:
array=np.random.randn(3,4)
array

array([[ 0.02235449, -0.19183596,  1.00016671,  0.63110214],
       [-0.35379451, -0.39285455,  0.44177729,  0.60238132],
       [-0.38001134, -0.24636137, -0.21336263, -0.51182316]])

In [20]:
np.round(array,decimals=3)

array([[ 0.022, -0.192,  1.   ,  0.631],
       [-0.354, -0.393,  0.442,  0.602],
       [-0.38 , -0.246, -0.213, -0.512]])

In [21]:
sports=np.array(['golf','cricket','fball','cricket','fball','basektball'])
np.unique(sports)

array(['basektball', 'cricket', 'fball', 'golf'], dtype='<U10')